import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_21_SOURCE = {
  week: 21,
  block: 4,
  title: "Strength Consolidation / Rebuild",
  days: [
    {
      day: 1,
      title: "BOX SQUAT + CLOSE-GRIP BENCH",
      role: "BOX SQUAT + CLOSE-GRIP BENCH",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Incline Walk or Bike — 5 minutes easy\nBackward Sled Drag — 3 trips x 20 yards light • knee-prep job\nMini-Band Lateral Walk — 2 x 10 • steps each direction\nGlute Bridge Isometric Hold — 2 x 20 seconds\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Hang Power Clean — 5 x 2 • 65%\nBox Jump — 3 x 2 • low fatigue\nBox Squat Primer — 2 x 2 • 55%\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Box Squat — consolidation volume\n1 x 5 @ 75%\n3 x 4 @ 70%\nClose-Grip Bench Press — triceps strength support\n4 x 5 @ 75%\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Hip Thrust — 4 x 8-10 • with 2-second pause\nSnatch-Grip RDL (or Hamstring Curl if recovery constrained) — 3 x 8-10",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row — 4 x 8-10\nLeg Extension — 3 x 12-15",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
    {
      day: 2,
      title: "BENCH VOLUME + INCLINE PRESS + BACK BALANCE",
      role: "BENCH VOLUME + INCLINE PRESS + BACK BALANCE",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes\nBand Pull-Apart — 2 x 20\nScapular Push-Up — 2 x 10\nFace Pull — 2 x 15\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Tall Clean or Muscle Clean — 3 x 3 • empty bar or very light\nHang Power Clean — 5 x 2 • 65%\nMedicine Ball Chest Pass — 3 x 3\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "ORDER NOTE: Complete protected Bench work first. Perform Strict OHP next, then return to any remaining source-primary support listed below.\n\nBench Press — upper-volume exposure\n4 x 5 @ 70%\nIncline Dumbbell Press\n3 x 8-10 @ RPE 7\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "III",
          title: "PRIMARY — STRICT OHP",
          priority: "mandatory",
          prescription: "3x5 @ 65%• DEVELOPMENT\nPLACEMENT: Day 2 AFTER protected Bench, BEFORE lower-priority support\nQUALITY: Stop at first grind, pppe, repeated layback/rib flare, loss of stacked lockout, or meaningful speed drop.",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable Press-Around",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Neutral-Grip Lat Pulldown — 4 x 8-10\nRear Deltoid Fly — 3 x 15",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "Chest-Supported Dumbbell Shrug or Kelso-Style Shrug — 3 x 10-12 • with 2-second squeeze",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
    {
      day: 3,
      title: "BLOCK PULL + FRONT SQUAT TECHNIQUE",
      role: "BLOCK PULL + FRONT SQUAT TECHNIQUE",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Walk — 5 minutes\nHip Hinge Drill — 2 x 10\nGlute Bridge — 2 x 15\nBird Dog — 2 x 8 each side\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Broad Jump — 3 x 2 • low fatigue\nKettlebell Swing — 2 x 8 • crisp\nDeadlift Primer — 2 x 2 • 55%\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Block Pull — strength wave\n1 x 5 @ 70%\n1 x 4 @ 75%\n1 x 3 @ 80%\n1 x 3 @ 82.5%\n1 x 4 @ 75%\nFront Squat Technique\n3 x 4 @ 65%\nAssisted Pull-Up or Pull-Up\n5 x 3-5 • clean reps\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row or Seated Cable Row — 4 x 8-12\nSeated Hamstring Curl — 3 x 10-15\nCONDITIONAL low-back durability: Sorenson Hold, Reverse Hyper, or Bird Dog Hold — 3 x 20-30 seconds",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–12 min easy walk/bike/elliptical only if it improves recovery",
        },
      ],
    },
    {
      day: 4,
      title: "RECOVERY + KNEES + HIP FLEXORS",
      role: "RECOVERY + KNEES + HIP FLEXORS",
      duration: "25–40 min core; ≤45–55 min with optional restoration",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 4–5 min\n90/90 Hip Switch — 1 x 6–8/side\nAnkle Rocker — 1 x 6–8/side",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "CONDITIONAL: Low Box Jump — 2 x 2 only if springy and pain-free; usually none in intensification/check/test/realization",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Recovery Primary — knees, hip flexors, and structural control only\nBackward Sled Drag\n5 x 20 yards • light to moderate\nLeg Extension\n3 x 15 • controlled, 2-second squeeze\nStanding Cable Hip Flexor March\n3 x 10 each leg\nRest - 45 to 60 seconds between movements",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Leg Extension — 3 x 12–15\nCable Hip-Flexor March — 3 x 8–10/leg",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Hamstring Curl — 2 x 10–12\nPallof Press OR Side Plank — 2 sets",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "mandatory",
          prescription: "Backward Sled Drag — 4 x 20 yd light-moderate • ONE total knee/recovery dose",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "OPTIONAL: hand health 1–2 easy sets only if weekly budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: choose ONE — 10–20 min easy walk/bike OR one short mobility/restoration flow. Leave feeling better.",
        },
      ],
    },
    {
      day: 5,
      title: "BELT SQUAT + PAUSE BENCH + CLEAN PULL",
      role: "BELT SQUAT + PAUSE BENCH + CLEAN PULL",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Mini-Band Lateral Walk — 2 x 10 • steps each direction\nBackward Sled Drag — 2 x 20 yards • light • knee-prep job\nGlute Bridge Isometric Hold — 2 x 20 seconds\nTibialis Raise — 2 x 15\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Hang Power Clean — 5 x 2 • 65%\nClean Pull — 4 x 2 • 95%\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Belt Squat Strength Volume\n3 x 8-10 @ RPE 7-8 • controlled\nPause Bench Press — reinforcement\n4 x 5 @ 75%\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable Press-Around — 2 to 3 x 10 to 15",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Lat Pulldown or Assisted Pull-Up — 3 x 8-10\nLeg Extension — 2 to 3 x 12 to 15",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "Farmer Carry (Trap-Bar Carry acceptable) — 3 to 4 x 30 yards, stop before grip breakdown",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
  ],
  sourceHash: "9f24d427e3c96e8f128eb83df1e836f9186a48156015c020ac354e017541c078",
} satisfies BlackCrownSourceWeek
