import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_17_SOURCE = {
  week: 17,
  block: 3,
  title: "Strength Peak / Intensification",
  days: [
    {
      day: 1,
      title: "FRONT SQUAT TOP SET + BENCH FREQUENCY",
      role: "Primary front squat strength exposure with bench frequency, posterior support, upper-back balance, and low-interference conditioning.",
      duration: "60–80 min; peak/realization support must not extend the session",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Incline Walk or Bike — 3 to 5 minutes easy\nBackward Sled Drag — 2 x 20 yards • light • knee-prep job\nMini-Band Lateral Walk — 2 x 10 • steps each direction\nGlute Bridge Isometric Hold — 2 x 20 seconds\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Front Squat Primer — 2 x 2 • 55%\nBox Jump — 2 x 2 • optional and low fatigue\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Front Squat — top set plus back-off\n1 x 3 @ 70%\n1 x 2 @ 75%\n1 x 1 @ 90%\n3 x 3 @ 82.5%\nBench Press — Sheiko frequency support\n4 x 4 @ 82.5%\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Hip Thrust — 2 x 8-10 • with 2-second pause",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row — 2 x 8-10",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
    {
      day: 2,
      title: "BENCH TOP SET + UPPER BACK SUPPORT",
      role: "Primary bench strength exposure with upper-back support, shoulder stability, and no high-intensity conditioning.",
      duration: "60–80 min; peak/realization support must not extend the session",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike — 5 minutes\nBand Pull-Apart — 2 x 20\nScapular Push-Up — 2 x 10\nFace Pull — 2 x 15\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Bench Press Primer — 2 x 2 • 55%\nExplosive Push-Up — 2 x 3 • crisp reps\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "ORDER NOTE: Complete protected Bench work first. Perform Strict OHP next, then return to any remaining source-primary support listed below.\n\nBench Press — top set plus back-off\n1 x 3 @ 70%\n1 x 2 @ 77.5%\n1 x 1 @ 90%\n3 x 3 @ 82.5%\nIncline Dumbbell Press\n2 x 8 @ RPE 7 • controlled\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "III",
          title: "PRIMARY — STRICT OHP",
          priority: "mandatory",
          prescription: "2x2 @ 77.5%• STRENGTH / INTENSIFICATION\nPLACEMENT: Day 2 AFTER protected Bench, BEFORE lower-priority support\nQUALITY: Stop at first grind, pain, repeated layback/rib flare, loss of stacked lockout, or meaningful speed drop.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Neutral-Grip Lat Pulldown — 4 x 8-10\nRear Deltoid Fly — 3 x 15",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "Chest-Supported Dumbbell Shrug or Kelso-Style Shrug — 2 x 10-12 • with 2-second squeeze",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
    {
      day: 3,
      title: "DEADLIFT TOP SET + LAT / POSTERIOR SUPPORT",
      role: "Primary deadlift strength exposure with upper-back support, back-extension role preservation, and limited grip fatigue.",
      duration: "60–80 min; peak/realization support must not extend the session",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Walk — 5 minutes\nHip Hinge Drill — 2 x 10\nGlute Bridge — 2 x 12\nBird Dog — 2 x 8 each side\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Broad Jump — 2 x 2 • optional and low fatigue\nKettlebell Swing — 2 x 8 • crisp reps\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Deadlift — top set plus back-off\n1 x 3 @ 70%\n1 x 2 @ 77.5%\n1 x 1 @ 90%\n3 x 3 @ 82.5%\nFront Squat Technique\n3 x 3 @ 67.5%\nAssisted Pull-Up or Pull-Up\n5 x 3-5 • clean reps\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row or Seated Cable Row — 3 x 8-12\nSeated Hamstring Curl — 2 x 10-15",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–12 min easy walk/bike/elliptical only if it improves recovery",
        },
      ],
    },
    {
      day: 4,
      title: "RECOVERY + KNEES + HIP FLEXORS",
      role: "Recovery-biased structural support. This is not another hinge day and not punishment conditioning.",
      duration: "25–40 min core; ≤45–55 min with optional restoration",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 4–5 min\n90/90 Hip Switch — 1 x 6–8/side\nAnkle Rocker — 1 x 6–8/side",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "CONDITIONAL: Low Box Jump — 2 x 2 only if springy and pain-free; usually none in intensification/check/test/realization",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Recovery Primary — knees, hip flexors, and structural control only\nBackward Sled Drag\n4 x 20 yards • light to moderate\nLeg Extension\n3 x 15 • controlled, 2-second squeeze\nStanding Cable Hip Flexor March\n3 x 10 each leg\nRest - 45 to 60 seconds between movements",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Leg Extension — 2 x 12–15\nCable Hip-Flexor March — 2 x 8–10/leg",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Hamstring Curl — 1–2 x 10–12\nPallof Press OR Side Plank — 1–2 sets",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "mandatory",
          prescription: "Backward Sled Drag — 2–3 x 20 yd light • ONE total knee/recovery dose",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "OPTIONAL: hand health 1–2 easy sets only if weekly budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: choose ONE — 10–20 min easy walk/bike OR one short mobility/restoration flow. Leave feeling better.",
        },
      ],
    },
    {
      day: 5,
      title: "STRENGTH REINFORCEMENT + CLEAN PULL SUPPORT",
      role: "Reinforce strength patterns, maintain Olympic derivative power, and finish the week without stealing recovery from the next block.",
      duration: "60–80 min; peak/realization support must not extend the session",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Incline Walk or Bike — 3 to 5 minutes easy\nBackward Sled Drag — 2 x 20 yards • light • knee-prep job\nMini-Band Lateral Walk — 2 x 10 • steps each direction\nGlute Bridge Isometric Hold — 2 x 20 seconds\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Hang Power Clean — 2 x 2 • 55%\nClean Pull — 3 x 2 • 90%\nClean pull standard - heavy loaded pull, powerful extension, clean positions, and no hitching. Do not turn this into an ugly deadlift.\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Secondary Squat Support — position and speed\n3 x 2 @ 75%\nPause Bench Press — reinforcement\n4 x 2 @ 80%\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable Press-Around — 2 to 3 x 10 to 15",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Lat Pulldown or Assisted Pull-Up — 3 x 8-10",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "CONDITIONAL if grip/traps are Green: Farmer Carry (Trap-Bar Carry acceptable) — 2 to 3 short trips, moderate only if grip is fresh",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
  ],
  sourceHash: "b530a99cb5ddcf5a8fda4bb30b4c1c364e27c13f695a07306cbd1bebcf1efc41",
} satisfies BlackCrownSourceWeek
