import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_42_SOURCE = {
  week: 42,
  block: 7,
  title: "Crazy Ivan Controlled Rebuild / Armor Density",
  days: [
    {
      day: 1,
      title: "BACK SQUAT + BENCH PERFORMANCE CHECK",
      role: "Back squat + bench performance check",
      duration: "45–60 min",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + Backward Sled 2x20 yd light + Hip Airplane 2x5/side",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump 3x2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Back Squat - performance single — 80% • 1 x 1\nBack Squat - back-off — 70% • 2 x 3\nBench Press - performance single — 80% • 1 x 1\nBench Press - back-off — 70% • 2 x 3\nRecord bar speed, technique, pain, and recovery. Do not calculate a new max. Continue the current TM when readiness is normal; reduce only when clearly necessary.",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Chest-Supported Row 2x10 RPE6 + Leg Extension 2x12 easy",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Trap-3 2x12 + Dead Bug 2x8/side only",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension optional only",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "10–15 min easy walk/bike optional",
        },
      ],
    },
    {
      day: 2,
      title: "UPPER-BACK / SHOULDER RECOVERY",
      role: "Upper-back / shoulder recovery",
      duration: "25–35 min",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "None",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Lat Pulldown\n2 x 12 @ RPE 6",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Chest-Supported Row 2x10 RPE6 + choose ONE: Face Pull OR Trap-3 2x12",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Mobility only if useful",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "No direct grip",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy walk 15–20 min optional",
        },
      ],
    },
    {
      day: 3,
      title: "DEADLIFT PERFORMANCE CHECK",
      role: "Deadlift performance check",
      duration: "40–55 min",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + Backward Sled 2x20 yd light + Hip Airplane 2x5/side + easy patterning",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump 3x2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Deadlift - performance single — 80% • 1 x 1\nDeadlift - back-off — 70% • 2 x 3\nRecord bar speed, technique, pain, and recovery. Do not calculate a new max.",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Chest-Supported Row 2x10 RPE6 + Leg Extension 2x12 easy",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Trap-3 2x12 + Dead Bug 2x8/side only",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension optional only",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "10–15 min easy walk/bike optional",
        },
      ],
    },
    {
      day: 4,
      title: "KNEES / HIP FLEXORS / RECOVERY",
      role: "Knees / hip flexors / recovery",
      duration: "20–30 min",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + 90/90 + ankle rocker",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "None",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Backward Sled Drag\n4 x 20 yards • light",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable March 2x10/side + Leg Extension 2x15 + Side Plank 2x20s/side",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Backward Sled 2–3x20 yd very light — ONE total dose",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "mandatory",
          prescription: "Backward Sled 2–3x20 yd very light — ONE total dose",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "No direct grip",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Optional restoration only",
        },
      ],
    },
    {
      day: 5,
      title: "FRONT SQUAT PERFORMANCE CHECK + BENCH TECHNIQUE",
      role: "Front-squat performance check + bench technique",
      duration: "45–60 min",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + Backward Sled 2x20 yd light + Hip Airplane 2x5/side + easy patterning",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump 3x2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Front Squat - performance single — 75% • 1 x 1\nFront Squat - back-off — 65% • 2 x 3\nBench Press - technique work — 65% • 3 x 3\nRecord bar speed, technique, pain, and recovery. Do not calculate a new max.",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Chest-Supported Row 2x10 RPE6 + Leg Extension 2x12 easy",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Trap-3 2x12 + Dead Bug 2x8/side only",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension optional only",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "10–15 min easy walk/bike optional",
        },
      ],
    },
  ],
  sourceHash: "62a59e619af2d65b07da1ddb72abae5405f4eaa3e4adfe2094196209a50a2c84",
} satisfies BlackCrownSourceWeek
