import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_48_SOURCE = {
  week: 48,
  block: 8,
  title: "Post-Realization Rebuild / Armor Accumulation",
  days: [
    {
      day: 1,
      title: "BACK SQUAT OPENER REHEARSAL",
      role: "Rehearse the planned Week 54 back-squat opener without creating a max or changing the training max.",
      duration: "20–60 min depending local test/check day",
      status: "OPENER REHEARSAL",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes\nBackward Sled Drag — 2 x 20 yards • light\nHip Airplane — 2 x 5 each side\nEmpty Bar Patterning — 2 easy sets",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump — 3 x 2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Back Squat - Generated Warm-Up Ramp — Finalize Week 54 projected third on MAXES\nBack Squat - Opener Rehearsal — Finalize Week 54 projected third on MAXES\nRecord speed, technique, confidence, and pain. Adjust the Week 54 projected third on MAXES if needed. Week 48 creates no verified 1RM and no TM change.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
    {
      day: 2,
      title: "BENCH PRESS OPENER REHEARSAL",
      role: "Rehearse the planned Week 54 bench opener with a controlled pause and no accumulated fatigue.",
      duration: "20–60 min depending local test/check day",
      status: "OPENER REHEARSAL",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes\nBackward Sled Drag — 2 x 20 yards • light\nHip Airplane — 2 x 5 each side\nEmpty Bar Patterning — 2 easy sets",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump — 3 x 2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Bench Press - Generated Warm-Up Ramp — Finalize Week 54 projected third on MAXES\nBench Press - Opener Rehearsal — Finalize Week 54 projected third on MAXES\nRecord speed, technique, confidence, and pain. Adjust the Week 54 projected third on MAXES if needed. Week 48 creates no verified 1RM and no TM change.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
    {
      day: 3,
      title: "RECOVERY / ATTEMPT-PLAN REVIEW",
      role: "Restore joints and finalize Week 54 projected third attempts on MAXES. No TM change.",
      duration: "20–60 min depending local test/check day",
      status: "OPENER REHEARSAL",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike — 10 minutes easy\n90/90 Hip Mobility — 2 x 5 each side\nSerratus Wall Slide — 2 x 10",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "None",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Mobility Flow — 2 easy rounds\nReview opener speed and confidence. Finalize Week 54 projected thirds in MAXES F48:F51. Week 48 creates no verified 1RM and no TM change.",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable March — 2 x 10 each side\nLeg Extension — 2 x 15 • easy",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
    {
      day: 4,
      title: "FRONT SQUAT OPENER REHEARSAL",
      role: "Rehearse the planned Week 54 front-squat opener with crisp positions and no extra loading.",
      duration: "20–60 min depending local test/check day",
      status: "OPENER REHEARSAL",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes\nBackward Sled Drag — 2 x 20 yards • light\nHip Airplane — 2 x 5 each side\nEmpty Bar Patterning — 2 easy sets",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump — 3 x 2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Front Squat - Generated Warm-Up Ramp — Finalize Week 54 projected third on MAXES\nFront Squat - Opener Rehearsal — Finalize Week 54 projected third on MAXES\nRecord speed, technique, confidence, and pain. Adjust the Week 54 projected third on MAXES if needed. Week 48 creates no verified 1RM and no TM change.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
    {
      day: 5,
      title: "DEADLIFT OPENER REHEARSAL",
      role: "Rehearse the planned Week 54 deadlift opener without accumulating grip or posterior-chain fatigue.",
      duration: "20–60 min depending local test/check day",
      status: "OPENER REHEARSAL",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes\nBackward Sled Drag — 2 x 20 yards • light\nHip Airplane — 2 x 5 each side\nEmpty Bar Patterning — 2 easy sets",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump — 3 x 2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Deadlift - Generated Warm-Up Ramp — Finalize Week 54 projected third on MAXES\nDeadlift - Opener Rehearsal — Finalize Week 54 projected third on MAXES\nRecord speed, technique, confidence, and pain. Adjust the Week 54 projected third on MAXES if needed. Week 48 creates no verified 1RM and no TM change.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
  ],
  sourceHash: "e258157f4b2b45e00a4b408a0de42102056ae27f06f50b701d36ccff21a63f12",
} satisfies BlackCrownSourceWeek
