import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_18_SOURCE = {
  week: 18,
  block: 3,
  title: "Strength Peak / Intensification",
  days: [
    {
      day: 1,
      title: "BACK SQUAT + BENCH PERFORMANCE CHECK",
      role: "Evaluate squat and bench quality at controlled submaximal loading. No verified 1RM or upward TM change.",
      duration: "20–60 min depending local test/check day",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes\nBackward Sled Drag — 2 x 20 yards • light\nHip Airplane — 2 x 5 each side",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump — 3 x 2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Back Squat - performance single — 80% • 1 x 1\nBack Squat - back-off — 70% • 2 x 3\nBench Press - performance single — 80% • 1 x 1\nBench Press - back-off — 70% • 2 x 3\nRecord bar speed, technique, pain, and recovery. Do not calculate a new max. Continue the current TM when readiness is normal; reduce only when clearly necessary.",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Chest-Supported Row — 2 x 10 • Effort cap: RPE 6\nLeg Extension — 2 x 12 • easy",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
    {
      day: 2,
      title: "UPPER-BACK / SHOULDER RECOVERY",
      role: "Restore pressing and pulling structures before the deadlift check.",
      duration: "20–60 min depending local test/check day",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "None",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Lat Pulldown\n2 x 12 @ RPE 6",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Chest-Supported Row — 2 x 10 • Effort cap: RPE 6\nFace Pull — 2 x 15",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
    {
      day: 3,
      title: "DEADLIFT PERFORMANCE CHECK",
      role: "Evaluate deadlift quality at controlled submaximal loading without creating a new max.",
      duration: "20–60 min depending local test/check day",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes\nBackward Sled Drag — 2 x 20 yards • light\nHip Airplane — 2 x 5 each side\nEmpty Bar Patterning — 2 easy sets",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump — 3 x 2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Deadlift - performance single — 80% • 1 x 1\nDeadlift - back-off — 70% • 2 x 3\nRecord bar speed, technique, pain, and recovery. Do not calculate a new max.",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Chest-Supported Row — 2 x 10 • Effort cap: RPE 6\nLeg Extension — 2 x 12 • easy",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
    {
      day: 4,
      title: "KNEES / HIP FLEXORS / RECOVERY",
      role: "Restore lower-body joints and trunk before the final check.",
      duration: "20–60 min depending local test/check day",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike — 5 minutes",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "None",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Backward Sled Drag\n4 x 20 yards • light",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable March — 2 x 10 each side\nLeg Extension — 2 x 15 • easy",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
    {
      day: 5,
      title: "FRONT SQUAT PERFORMANCE CHECK + BENCH TECHNIQUE",
      role: "Evaluate front-squat quality and preserve bench skill without adding peak fatigue.",
      duration: "20–60 min depending local test/check day",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes\nBackward Sled Drag — 2 x 20 yards • light\nHip Airplane — 2 x 5 each side\nEmpty Bar Patterning — 2 easy sets",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump — 3 x 2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Front Squat - performance single — 75% • 1 x 1\nFront Squat - back-off — 65% • 2 x 3\nBench Press - technique work — 65% • 3 x 3\nRecord bar speed, technique, pain, and recovery. Do not calculate a new max.",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Chest-Supported Row — 2 x 10 • Effort cap: RPE 6\nLeg Extension — 2 x 12 • easy",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
  ],
  sourceHash: "365a055d156263133cb84c9046ab9632013cf822f6cce45000d9a233918b77e8",
} satisfies BlackCrownSourceWeek
