import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_06_SOURCE = {
  week: 6,
  block: 1,
  title: "Foundation / Re-Entry",
  days: [
    {
      day: 1,
      title: "LOWER + BENCH FREQUENCY + GLUTES",
      role: "Deload lower-body and bench skill while keeping the sled/glute/knee primer and easy posterior support.",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Incline Walk or Bike — 3 to 5 minutes easy\nBackward Sled Drag — 2 x 20 yards • light • knee-prep job\nMini-Band Lateral Walk — 2 x 10 • steps each direction\nGlute Bridge Isometric Hold — 2 x 20 seconds\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Hang Power Clean — 3 x 2 • 55%\nBox Jump — 2 x 2 • low fatigue\nKettlebell Swing — 2 x 8 • easy reps\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Front Squat — Sheiko base deload exposure\n3 x 5 @ 60%\nBench Press — technique volume\n3 x 5 @ 60%\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Hip Thrust or Glute Bridge — 2 x 10 • easy with 2-second pause\nSeated Hamstring Curl — 2 x 12 • controlled",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row — 2 x 10\nLeg Extension — 2 x 15 • easy\nCONDITIONAL: Step-Up — 6 each leg",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
    {
      day: 2,
      title: "BENCH VOLUME + UPPER BACK / YOKE / ARMS",
      role: "Easy upper-body pump, shoulder support, and low-fatigue rotational skill. Day 2 stays recovery-friendly.",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike — 5 minutes\nBand Pull-Apart — 2 x 20\nScapular Push-Up — 2 x 8\nFace Pull — 2 x 12\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Medicine Ball Chest Pass — 2 x 3 • easy\nExplosive Push-Up — 2 x 3 • easy\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "ORDER NOTE: Complete protected Bench work first. Perform Strict OHP next, then return to any remaining source-primary support listed below.\n\nBench Press — deload technique exposure\n3 x 5 @ 60%\nIncline Dumbbell Press\n2 x 10 @ RPE 6 • easy\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "III",
          title: "PRIMARY — STRICT OHP",
          priority: "mandatory",
          prescription: "2x5 @ 55%• DEVELOPMENT\nPLACEMENT: Day 2 AFTER protected Bench, BEFORE lower-priority support\nQUALITY: Stop at first grind, pain, repeated layback/rib flare, loss of stacked lockout, or meaningful speed drop.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Neutral-Grip Lat Pulldown — 2 x 8-10\nRear Deltoid Fly — 2 x 15",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "Chest-Supported Dumbbell Shrug or Kelso-Style Shrug — 1 x 10-12 • with 2-second squeeze",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
    {
      day: 3,
      title: "DEADLIFT + SECONDARY SQUAT + PULL",
      role: "Deload posterior chain while preserving deadlift skill, upper-back work, and back-extension role without fatigue.",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Walk — 5 minutes\nHip Hinge Drill — 2 x 10\nGlute Bridge — 2 x 12\nBird Dog — 2 x 8 each side\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Broad Jump — 2 x 2 • easy\nKettlebell Swing — 2 x 8 • easy reps\nDeadlift Primer — 2 x 2 • 50%\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Deadlift — deload technique exposure\n3 x 3 @ 60%\nFront Squat Technique\n2 x 4 @ 60%\nAssisted Pull-Up or Pull-Up\n5 x 3-5 • clean reps\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Seated Hamstring Curl — 2 x 12 • controlled\nCONDITIONAL low-back durability: Sorenson Hold or Bird Dog Hold — 2 x 20 seconds",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–12 min easy walk/bike/elliptical only if it improves recovery",
        },
      ],
    },
    {
      day: 4,
      title: "RECOVERY + KNEES + HIP FLEXORS",
      role: "Recovery day for joints, hip flexors, trunk control, and knee blood flow. This should leave you better than you started.",
      duration: "25–40 min core; ≤45–55 min with optional restoration",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 4–5 min\n90/90 Hip Switch — 1 x 6–8/side\nAnkle Rocker — 1 x 6–8/side",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "CONDITIONAL: Low Box Jump — 2 x 2 only if springy and pain-free; usually none in intensification/check/test/realization",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Recovery Primary — knees, hip flexors, and structural control only\nBackward Sled Drag\n3 x 20 yards • light\nLeg Extension\n2 x 15 • easy\nStanding Cable Hip Flexor March\n2 x 10 each leg\nRest - 45 to 60 seconds between movements",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Leg Extension — 3 x 12–15\nCable Hip-Flexor March — 3 x 8–10/leg",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Hamstring Curl — 2 x 10–12\nPallof Press OR Side Plank — 2 sets",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "mandatory",
          prescription: "Backward Sled Drag — 4 x 20 yd light • ONE total knee/recovery dose",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "OPTIONAL: hand health 1–2 easy sets only if weekly budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: choose ONE — 10–20 min easy walk/bike OR one short mobility/restoration flow. Leave feeling better.",
        },
      ],
    },
    {
      day: 5,
      title: "SECONDARY SQUAT + CLOSE-GRIP BENCH + CARRY",
      role: "Finish the deload with easy full-body rhythm, clean technique, knee-friendly sled work, and no fatigue spillover.",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Bike or Walk — 3 to 5 minutes easy\nBackward Sled Drag — 2 x 20 yards • light • knee-prep job\nMini-Band Lateral Walk — 2 x 10 • steps each direction\nGlute Bridge Isometric Hold — 2 x 20 seconds\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Hang Power Clean — 3 x 2 • 55%\nClean Pull — 3 x 3 • 60%\nExplosive Push-Up — 2 x 3 • easy\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Belt Squat or Goblet Squat\n2 x 10 @ RPE 6 • easy\nPause Bench Press — deload reinforcement\n3 x 5 @ 60%\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable Press-Around — 2 x 12 • easy",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Lat Pulldown — 2 x 10 • easy\nLeg Extension — 2 x 15 • easy",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "Farmer Carry (Trap-Bar Carry acceptable) — 1 to 2 easy trips only if grip is fresh",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Prowler Push — 3 x 20 yards • easy • work-capacity job only",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
  ],
  sourceHash: "af79adedd675baec839b48cdefef08f48836c3a9a1f9a550112e481b19df3c04",
} satisfies BlackCrownSourceWeek
