import { BLACK_CROWN_WEEK_01_SOURCE } from './week-01'
import { BLACK_CROWN_WEEK_02_SOURCE } from './week-02'
import { BLACK_CROWN_WEEK_03_SOURCE } from './week-03'
import { BLACK_CROWN_WEEK_04_SOURCE } from './week-04'
import { BLACK_CROWN_WEEK_05_SOURCE } from './week-05'
import { BLACK_CROWN_WEEK_06_SOURCE } from './week-06'
import { BLACK_CROWN_WEEK_07_SOURCE } from './week-07'
import { BLACK_CROWN_WEEK_08_SOURCE } from './week-08'
import { BLACK_CROWN_WEEK_09_SOURCE } from './week-09'
import { BLACK_CROWN_WEEK_10_SOURCE } from './week-10'
import { BLACK_CROWN_WEEK_11_SOURCE } from './week-11'
import { BLACK_CROWN_WEEK_12_SOURCE } from './week-12'
import { BLACK_CROWN_WEEK_13_SOURCE } from './week-13'
import { BLACK_CROWN_WEEK_14_SOURCE } from './week-14'
import { BLACK_CROWN_WEEK_15_SOURCE } from './week-15'
import { BLACK_CROWN_WEEK_16_SOURCE } from './week-16'
import { BLACK_CROWN_WEEK_17_SOURCE } from './week-17'
import { BLACK_CROWN_WEEK_18_SOURCE } from './week-18'
import { BLACK_CROWN_WEEK_19_SOURCE } from './week-19'
import { BLACK_CROWN_WEEK_20_SOURCE } from './week-20'
import { BLACK_CROWN_WEEK_21_SOURCE } from './week-21'
import { BLACK_CROWN_WEEK_22_SOURCE } from './week-22'
import { BLACK_CROWN_WEEK_23_SOURCE } from './week-23'
import { BLACK_CROWN_WEEK_24_SOURCE } from './week-24'
import { BLACK_CROWN_WEEK_25_SOURCE } from './week-25'
import { BLACK_CROWN_WEEK_26_SOURCE } from './week-26'
import { BLACK_CROWN_WEEK_27_SOURCE } from './week-27'
import { BLACK_CROWN_WEEK_28_SOURCE } from './week-28'
import { BLACK_CROWN_WEEK_29_SOURCE } from './week-29'
import { BLACK_CROWN_WEEK_30_SOURCE } from './week-30'
import { BLACK_CROWN_WEEK_31_SOURCE } from './week-31'
import { BLACK_CROWN_WEEK_32_SOURCE } from './week-32'
import { BLACK_CROWN_WEEK_33_SOURCE } from './week-33'
import { BLACK_CROWN_WEEK_34_SOURCE } from './week-34'
import { BLACK_CROWN_WEEK_35_SOURCE } from './week-35'
import { BLACK_CROWN_WEEK_36_SOURCE } from './week-36'
import { BLACK_CROWN_WEEK_37_SOURCE } from './week-37'
import { BLACK_CROWN_WEEK_38_SOURCE } from './week-38'
import { BLACK_CROWN_WEEK_39_SOURCE } from './week-39'
import { BLACK_CROWN_WEEK_40_SOURCE } from './week-40'
import { BLACK_CROWN_WEEK_41_SOURCE } from './week-41'
import { BLACK_CROWN_WEEK_42_SOURCE } from './week-42'
import { BLACK_CROWN_WEEK_43_SOURCE } from './week-43'
import { BLACK_CROWN_WEEK_44_SOURCE } from './week-44'
import { BLACK_CROWN_WEEK_45_SOURCE } from './week-45'
import { BLACK_CROWN_WEEK_46_SOURCE } from './week-46'
import { BLACK_CROWN_WEEK_47_SOURCE } from './week-47'
import { BLACK_CROWN_WEEK_48_SOURCE } from './week-48'
import { BLACK_CROWN_WEEK_49_SOURCE } from './week-49'
import { BLACK_CROWN_WEEK_50_SOURCE } from './week-50'
import { BLACK_CROWN_WEEK_51_SOURCE } from './week-51'
import { BLACK_CROWN_WEEK_52_SOURCE } from './week-52'
import { BLACK_CROWN_WEEK_53_SOURCE } from './week-53'
import { BLACK_CROWN_WEEK_54_SOURCE } from './week-54'

export const BLACK_CROWN_SOURCE_WEEKS = [
  BLACK_CROWN_WEEK_01_SOURCE,
  BLACK_CROWN_WEEK_02_SOURCE,
  BLACK_CROWN_WEEK_03_SOURCE,
  BLACK_CROWN_WEEK_04_SOURCE,
  BLACK_CROWN_WEEK_05_SOURCE,
  BLACK_CROWN_WEEK_06_SOURCE,
  BLACK_CROWN_WEEK_07_SOURCE,
  BLACK_CROWN_WEEK_08_SOURCE,
  BLACK_CROWN_WEEK_09_SOURCE,
  BLACK_CROWN_WEEK_10_SOURCE,
  BLACK_CROWN_WEEK_11_SOURCE,
  BLACK_CROWN_WEEK_12_SOURCE,
  BLACK_CROWN_WEEK_13_SOURCE,
  BLACK_CROWN_WEEK_14_SOURCE,
  BLACK_CROWN_WEEK_15_SOURCE,
  BLACK_CROWN_WEEK_16_SOURCE,
  BLACK_CROWN_WEEK_17_SOURCE,
  BLACK_CROWN_WEEK_18_SOURCE,
  BLACK_CROWN_WEEK_19_SOURCE,
  BLACK_CROWN_WEEK_20_SOURCE,
  BLACK_CROWN_WEEK_21_SOURCE,
  BLACK_CROWN_WEEK_22_SOURCE,
  BLACK_CROWN_WEEK_23_SOURCE,
  BLACK_CROWN_WEEK_24_SOURCE,
  BLACK_CROWN_WEEK_25_SOURCE,
  BLACK_CROWN_WEEK_26_SOURCE,
  BLACK_CROWN_WEEK_27_SOURCE,
  BLACK_CROWN_WEEK_28_SOURCE,
  BLACK_CROWN_WEEK_29_SOURCE,
  BLACK_CROWN_WEEK_30_SOURCE,
  BLACK_CROWN_WEEK_31_SOURCE,
  BLACK_CROWN_WEEK_32_SOURCE,
  BLACK_CROWN_WEEK_33_SOURCE,
  BLACK_CROWN_WEEK_34_SOURCE,
  BLACK_CROWN_WEEK_35_SOURCE,
  BLACK_CROWN_WEEK_36_SOURCE,
  BLACK_CROWN_WEEK_37_SOURCE,
  BLACK_CROWN_WEEK_38_SOURCE,
  BLACK_CROWN_WEEK_39_SOURCE,
  BLACK_CROWN_WEEK_40_SOURCE,
  BLACK_CROWN_WEEK_41_SOURCE,
  BLACK_CROWN_WEEK_42_SOURCE,
  BLACK_CROWN_WEEK_43_SOURCE,
  BLACK_CROWN_WEEK_44_SOURCE,
  BLACK_CROWN_WEEK_45_SOURCE,
  BLACK_CROWN_WEEK_46_SOURCE,
  BLACK_CROWN_WEEK_47_SOURCE,
  BLACK_CROWN_WEEK_48_SOURCE,
  BLACK_CROWN_WEEK_49_SOURCE,
  BLACK_CROWN_WEEK_50_SOURCE,
  BLACK_CROWN_WEEK_51_SOURCE,
  BLACK_CROWN_WEEK_52_SOURCE,
  BLACK_CROWN_WEEK_53_SOURCE,
  BLACK_CROWN_WEEK_54_SOURCE,
] as const
