import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_44_SOURCE = {
  week: 44,
  block: 8,
  title: "Post-Realization Rebuild / Armor Accumulation",
  days: [
    {
      day: 1,
      title: "PAUSE BACK SQUAT + PAUSE BENCH",
      role: "PAUSE BACK SQUAT + PAUSE BENCH",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Bike or Incline Walk — 3-5 min\nBackward Sled Drag — 2 trips x 20 yards • knee-prep job\nMini-Band Lateral Walk — 10 steps each direction\nGlute Bridge Iso Hold — 20 sec\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Box Jump — 3 x 3 • low fatigue\nKB Swing — 2 x 10 • crisp hinge\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Pause Back Squat — Sheiko return wave\n1 x 5 @ 72.5%\n3 x 4 @ 67.5%\nTwo-Count Pause Bench Press — frequency volume\n70% / x 5; 75% / x 4; 80% / x 3; 75% / x 4; 70% / x 5\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Hip Thrust — 3 x 8-10 • with 2-second pause\nSnatch-Grip RDL (or Hamstring Curl if recovery constrained) — 3 x 8-10",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row — 3 x 8-10\nLeg Extension — 3 x 12-15",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
    {
      day: 2,
      title: "BENCH VOLUME + CONTROLLED YOKE / ARMS",
      role: "BENCH VOLUME + CONTROLLED YOKE / ARMS",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 min\nBand Pull-Apart — 2 x 15\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Explosive Push-Up — 3 x 4 • crisp reps\nMed Ball Chest Pass or Plyo Push-Up — 3 x 3 • if available\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "ORDER NOTE: Complete protected Bench work first. Perform Strict OHP next, then return to any remaining source-primary support listed below.\n\nBench Press — full Crown Pyramid Density Wave\n70% / x 5; 75% / x 4; 80% / x 3; 75% / x 4; 70% / x 5\nIncline Dumbbell Press\n3 x 8-10 @ RPE 7-8\nChest-Supported Row\n4 x 8-10\nRest - 60 to 90 seconds through 75%; 2 to 3 minutes from 77.5% through the apex; return to 60 to 90 seconds on descending sets only while bar speed stays clean.",
        },
        {
          ordinal: "III",
          title: "PRIMARY — STRICT OHP",
          priority: "mandatory",
          prescription: "3x5 @ 65%• DEVELOPMENT\nPLACEMENT: Day 2 AFTER protected Bench, BEFORE lower-priority support\nQUALITY: Stop at first grind, pain, repeated layback/rib flare, loss of stacked lockout, or meaningful speed drop.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Neutral-Grip Lat Pulldown — 4 x 8-10\nRear Deltoid Fly — 3 x 15",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "Chest-Supported Dumbbell Shrug or Kelso-Style Shrug — 3 x 10-12 • with 2-second squeeze",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
    {
      day: 3,
      title: "PAUSED DEADLIFT + PULL / POSTERIOR",
      role: "PAUSED DEADLIFT + PULL / POSTERIOR",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Walk — 5 min\nHip Hinge Drill — 10 reps\nGlute Bridge — 2 x 12\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Broad Jump — 3 x 3 • low fatigue\nKB Dead-Stop Swing — 2 x 8\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Paused Deadlift — strength wave\n1 x 5 @ 67.5%\n1 x 5 @ 72.5%\n1 x 4 @ 77.5%\n1 x 3 @ 80%\n1 x 5 @ 72.5%\nFront Squat Technique\n3 x 4 @ 62.5%\nAssisted Pull-Up or Pull-Up\n5 x 3-5 • clean reps\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row or Seated Cable Row — 4 x 8-12\nSeated Hamstring Curl — 3 x 10-15\nCONDITIONAL low-back durability: Sorenson Hold, Reverse Hyper, or Bird Dog Hold — 3 x 20-30 seconds",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–12 min easy walk/bike/elliptical only if it improves recovery",
        },
      ],
    },
    {
      day: 4,
      title: "RECOVERY + KNEES + HIP FLEXORS",
      role: "RECOVERY + KNEES + HIP FLEXORS",
      duration: "25–40 min core; ≤45–55 min with optional restoration",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 4–5 min\n90/90 Hip Switch — 1 x 6–8/side\nAnkle Rocker — 1 x 6–8/side",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "CONDITIONAL: Low Box Jump — 2 x 2 only if springy and pain-free; usually none in intensification/check/test/realization",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Recovery Primary — knees, hip flexors, and structural control only\nBackward Sled Drag\n4 x 20 yards • light to moderate\nLeg Extension\n3 x 15 • controlled, 2-second squeeze\nStanding Cable Hip Flexor March\n3 x 10 each leg\nRest - 45 to 60 seconds between movements",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Leg Extension — 2–3 x 12–15\nCable Hip-Flexor March — 2–3 x 8–10/leg",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Hamstring Curl — 2 x 10–12\nPallof Press OR Side Plank — 2 sets",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "mandatory",
          prescription: "Backward Sled Drag — 4 x 20 yd light-moderate • ONE total knee/recovery dose",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "OPTIONAL: hand health 1–2 easy sets only if weekly budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: choose ONE — 10–20 min easy walk/bike OR one short mobility/restoration flow. Leave feeling better.",
        },
      ],
    },
    {
      day: 5,
      title: "FRONT SQUAT SUPPORT + CLEAN PULL + LOADED YOKE",
      role: "FRONT SQUAT SUPPORT + CLEAN PULL + LOADED YOKE",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Bike or Walk — 3-5 min\nBackward Sled Drag — 2 trips x 20 yards • knee-prep job\nMini-Band Lateral Walk — 10 steps each direction\nGlute Bridge Iso Hold — 20 sec\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Hang Power Clean — 5 x 2 • 65%\nClean Pull — 4 x 3 • 75%\nClean Pull standard - strong extension, clean posture, aggressive intent, no hitching.\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Belt Squat Strength Volume\n3 x 8-10 @ RPE 7-8 • controlled\nPause Bench Press — reinforcement\n4 x 5 @ 72.5%\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable Press-Around — 2 to 3 x 10 to 15",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Lat Pulldown or Assisted Pull-Up — 3 x 8-10\nLeg Extension — 2 to 3 x 12 to 15",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "Farmer Carry (Trap-Bar Carry acceptable) — 3 to 4 x 30 yards, stop before grip breakdown",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Sled Push — 3-4 trips x 20 yards • work-capacity job only",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
  ],
  sourceHash: "7f3bd9c6e5dbe0c6c14ee5bb3b043acc255162b158ddcb58c8e6c825d38e0f5d",
} satisfies BlackCrownSourceWeek
