import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_30_SOURCE = {
  week: 30,
  block: 5,
  title: "Powerbuilding / Weak-Point Accumulation + Yoke",
  days: [
    {
      day: 1,
      title: "BACK SQUAT + BENCH PERFORMANCE CHECK",
      role: "Back squat + bench performance check",
      duration: "45–60 min",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + Backward Sled 2x20 yd light + Hip Airplane 2x5/side",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump 3x2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Back Squat - performance single — 80% • 1 x 1\nBack Squat - back-off — 70% • 2 x 3\nBench Press - performance single — 80% • 1 x 1\nBench Press - back-off — 70% • 2 x 3\nRecord bar speed, technique, pain, and recovery. Do not calculate a new max. Continue the current TM when readiness is normal; reduce only when clearly necessary.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row 2x10 RPE6 + Leg Extension 2x12 easy + Trap-3 2x12 + Dead Bug 2x8/side",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension 2x20 optional/low priority",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "10–15 min easy walk/bike optional",
        },
      ],
    },
    {
      day: 2,
      title: "UPPER-BACK / SHOULDER RECOVERY",
      role: "Upper-back / shoulder recovery",
      duration: "30–40 min",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "None",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Lat Pulldown\n2 x 12 @ RPE 6",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row 2x10 RPE6 + Face Pull 2x15 + Trap-3 2x12",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy Walk 15–20 min optional",
        },
      ],
    },
    {
      day: 3,
      title: "DEADLIFT PERFORMANCE CHECK",
      role: "Deadlift performance check",
      duration: "40–55 min",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + Backward Sled 2x20 yd light + Hip Airplane 2x5/side + patterning",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump 3x2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Deadlift - performance single — 80% • 1 x 1\nDeadlift - back-off — 70% • 2 x 3\nRecord bar speed, technique, pain, and recovery. Do not calculate a new max.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row 2x10 RPE6 + Leg Extension 2x12 easy + Trap-3 2x12 + Dead Bug 2x8/side",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension 2x20 optional/low priority",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "10–15 min easy walk/bike optional",
        },
      ],
    },
    {
      day: 4,
      title: "KNEES / HIP FLEXORS / RECOVERY",
      role: "Knees / hip flexors / recovery",
      duration: "25–35 min",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "None",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Backward Sled Drag\n4 x 20 yards • light",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Leg Extension 2x15 easy + Cable March 2x10/side + Side Plank 2x20s/side",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "mandatory",
          prescription: "Backward Sled 2–3x20 yd very light; local check-week rule overrides normal B5 core",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "No direct grip",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Optional restoration only",
        },
      ],
    },
    {
      day: 5,
      title: "FRONT SQUAT PERFORMANCE CHECK + BENCH TECHNIQUE",
      role: "Front squat performance check + bench technique",
      duration: "45–60 min",
      status: "NON-MAX CHECK",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + Backward Sled 2x20 yd light + Hip Airplane 2x5/side + patterning",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump 3x2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Front Squat - performance single — 75% • 1 x 1\nFront Squat - back-off — 65% • 2 x 3\nBench Press - technique work — 65% • 3 x 3\nRecord bar speed, technique, pain, and recovery. Do not calculate a new max.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row 2x10 RPE6 + Leg Extension 2x12 easy + Trap-3 2x12 + Dead Bug 2x8/side",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension 2x20 optional/low priority",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "10–15 min easy walk/bike optional",
        },
      ],
    },
  ],
  sourceHash: "9350fb003575e9e5f60ac1b3392a0e856adcf58c6d6344b0f156571ed103b380",
} satisfies BlackCrownSourceWeek
