import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_39_SOURCE = {
  week: 39,
  block: 7,
  title: "Crazy Ivan Controlled Rebuild / Armor Density",
  days: [
    {
      day: 1,
      title: "SQUAT / BENCH DENSITY BASE",
      role: "Squat / bench density base",
      duration: "65–80 min",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + Backward Sled 2x20 yd light (knee-prep job) + Hip Airplane 1–2x5/side + lift ramps",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Box Jump 3x2 + Med-Ball Chest Pass 3x3; crisp only",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Front Squat — compressed pyramid density wave\n65% / x 5; 70% / x 4; 75% / x 3; 77.5% / x 2; 72.5% / x 3; 67.5% / x 4\nBench Press — technique mini pyramid\n65% / x 5; 72.5% / x 4; 77.5% / x 3; 70% / x 5\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "III",
          title: "PRIMARY — STRICT OHP",
          priority: "mandatory",
          prescription: "2x3 @ 62.5%• MAINTENANCE MICRODOSE\nPLACEMENT: Day 1 AFTER Bench mini-pyramid\nQUALITY: If Day-1 density quality falls, omit OHP; no make-up.",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "REPLACED BY STRICT OHP THIS WEEK — omit Step-Up + Pallof support layer.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension 1–2 sets OPTIONAL only if weekly hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "None by default; 8–10 min easy walk/bike only if it improves recovery",
        },
      ],
    },
    {
      day: 2,
      title: "UPPER DENSITY + YOKE / ARMS",
      role: "Upper density + controlled yoke",
      duration: "70–90 min",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + choose 2: Band Pull-Apart / Serratus Wall Slide / Scap Push-Up + bench ramp",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Hang Power Clean 3x2 RPE 6; Tall/Muscle Clean drill optional only if technique needs it",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Bench Press — full Crown Pyramid Density Wave\n62.5% / x 5; 67.5% / x 5; 72.5% / x 4; 77.5% / x 4; 82.5% / x 3; 82.5% / x 2; 80% / x 3; 75% / x 4; 70% / x 5; 65% / x 5\nIncline Dumbbell Press\n3 x 8-10 @ RPE 7-8\nChest-Supported Row\n4 x 8-10\nRest - 60 to 90 seconds through 75%; 2 to 3 minutes from 77.5% through the apex; return to 60 to 90 seconds on descending sets only while bar speed stays clean.",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Chest-Supported/Kelso Shrug 3x10–12 + Trap-3 2x10",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Optional curl + pushdown 1–2x10–12 only if Green and session time is available",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "mandatory",
          prescription: "Direct yoke only; no loaded carry",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "No loaded grip; finger extension optional",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "No separate circuit + cardio stack; choose 8–12 min easy bike/walk only if desired",
        },
      ],
    },
    {
      day: 3,
      title: "DEADLIFT SPEED + POSTERIOR / PULL",
      role: "Speed deadlift + posterior / pull",
      duration: "65–80 min",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + Hip Hinge Drill 1x8–10 + Glute Bridge 1x12 + deadlift ramp",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Broad Jump 3x2; KB Swing 2x8 OPTIONAL only if hinge feels crisp",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Speed Deadlift — Crazy Ivan speed / position work\n8 x 2 @ 65%\nFront Squat Technique\n3 x 4 @ 62.5%\nAssisted Pull-Up or Pull-Up\n5 x 3-5 • clean reps\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Ham Curl 2x10–12 + Chest-Supported Row 2–3x8–10",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "No arms by default; optional Bird-Dog/Sorenson 1–2 easy sets only if it improves low-back readiness",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "No carry; speed deadlift/pull-up/row already earn yoke + grip credit",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Choose ONE: 8–10 min easy sled drag OR 8–10 min walk/elliptical",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension 1–2 sets OPTIONAL; no holds",
        },
      ],
    },
    {
      day: 4,
      title: "RECOVERY + KNEES + HIP FLEXORS",
      role: "Recovery + knees + hip flexors",
      duration: "25–35 min core; ≤45 min with restoration",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 4–5 min\n90/90 Hip Switch — 1 x 6–8/side\nAnkle Rocker — 1 x 6–8/side",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "CONDITIONAL: Low Box Jump — 2 x 2 only if springy and pain-free; usually none in intensification/check/test/realization",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Recovery Primary — knees, hip flexors, and structural control only\nBackward Sled Drag\n5 x 20 yards • light to moderate\nLeg Extension\n3 x 15 • controlled, 2-second squeeze\nStanding Cable Hip Flexor March\n3 x 10 each leg\nRest - 45 to 60 seconds between movements",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Leg Extension — 2 x 12–15\nCable Hip-Flexor March — 2 x 8–10/leg",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Hamstring Curl — 2 x 10–12\nPallof Press OR Side Plank — 2 sets",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "mandatory",
          prescription: "Backward Sled Drag — 3 x 20 yd light • ONE total knee/recovery dose",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "OPTIONAL: hand health 1–2 easy sets only if weekly budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: choose ONE — 10–20 min easy walk/bike OR one short mobility/restoration flow. Leave feeling better.",
        },
      ],
    },
    {
      day: 5,
      title: "CARRY / SLED ARMOR + SECONDARY BENCH",
      role: "Primary armor / carry + secondary bench",
      duration: "70–90 min",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "3–5 min easy + 2 day-specific prep drills + carry/bench ramp; no warm-up sled layer",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Hang Power Clean 3x2 RPE6 + Clean Pull 3x2 @90%",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Trap Bar Carry or Farmer Carry\n4 x 30 yards • controlled, rest as needed\nClose-Grip Bench Press — density support\n4 x 5 @ 70%\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable Press-Around 2x12–15 + Lat Pulldown 2–3x8–10",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "No extra leg/glute accessory layer in Block 7",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "mandatory",
          prescription: "The source primary 4x30 yd carry IS the weekly loaded-carry exposure; no second carry slot or shrug circuit",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Sled Push 2x20 yd only if Green",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "No Plate Pinch by default; finger extension optional only if hands are fresh",
        },
      ],
    },
  ],
  sourceHash: "f163fbe4e40258342c1cedfcfeb7d29f5c589857bc0c64b564537c20225d3c98",
} satisfies BlackCrownSourceWeek
