import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_26_SOURCE = {
  week: 26,
  block: 5,
  title: "Powerbuilding / Weak-Point Accumulation + Yoke",
  days: [
    {
      day: 1,
      title: "SMOLOV-LITE SQUAT VOLUME + BENCH",
      role: "Smolov-lite squat volume + bench",
      duration: "75–90 min",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + Backward Sled Drag 2x20 yd (knee-prep job) + 2 prep drills + squat/bench ramp",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Box Jump 3x3 + Med-Ball Chest Pass 3x3–5, crisp",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Back Squat — Smolov-lite volume focus\n5 x 5 @ 72.5%\nBench Press — strength maintenance\n4 x 5 @ 72.5%\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "None beyond protected bench today",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Hip Thrust 3x8–10 + Reverse Lunge 2x8/leg\nChest-Supported Row 2x8–10 + Pallof 2x10/side",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "None; save yoke/grip for D2/D5",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Optional finger extension 1–2 sets only if weekly hand-health budget open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "No mandatory finisher; optional 8–10 min easy walk/bike",
        },
      ],
    },
    {
      day: 2,
      title: "UPPER POWERBUILDING + YOKE / ARMS",
      role: "Upper powerbuilding + focused chest + direct yoke",
      duration: "75–90 min",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + Band Pull-Apart 2x15–20 + Serratus Wall Slide 2x8–10 + bench ramp",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Hang Power Clean 4x2 RPE5–6; Tall/Muscle Clean 2x3 OPTIONAL if technique needs it",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Bench Press — full Crown Pyramid Density Wave\n4 x 6 @ 70%\nIncline Dumbbell Press\n3 x 8-10 @ RPE 7-8\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Incline DB Press 3x8–10 (Exposure A)",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Neutral-Grip Pulldown 3x8–10 + Rear Delt 2x15 + External Rotation 2x12 + Curl 2x10–12 + Pushdown 2x10–12",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "mandatory",
          prescription: "Chest-Supported Shrug 3x10–12 + Trap-3 Raise 2x10",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Optional hand-health only; no loaded grip",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Optional 10–15 min easy walk/bike only",
        },
      ],
    },
    {
      day: 3,
      title: "DEADLIFT CONTROL + PULL / POSTERIOR",
      role: "Deadlift strength + pull / posterior",
      duration: "75–90 min",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "5 min easy + Hip Hinge Drill 1x8–10 + Glute Bridge 1x12 + deadlift ramp",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Broad Jump 3x2 + KB Swing 2x10, crisp",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Deadlift — strength wave\n1 x 5 @ 67.5%\n1 x 5 @ 72.5%\n1 x 4 @ 77.5%\n1 x 3 @ 80%\n1 x 5 @ 72.5%\nFront Squat Technique\n3 x 4 @ 62.5%\nAssisted Pull-Up or Pull-Up\n5 x 3-5 • clean reps\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Deadlift supplies high-fatigue lengthened/posterior role; no extra SG-RDL slot\nChest-Supported Row 3x8–12; OPTIONAL Sorenson/Bird-Dog Hold 1–2x20–30s if low back feels better afterward",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "No carry; hard pulling already earns yoke/grip credit",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Choose ONE: 8–12 min easy elliptical/sled-drag OR 10 min walk; not both",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension 1–2 sets OPTIONAL; no holds",
        },
      ],
    },
    {
      day: 4,
      title: "RECOVERY + KNEES + HIP FLEXORS",
      role: "Recovery + knees + hip flexors",
      duration: "30–40 min core; ≤50 with restoration",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 4–5 min\n90/90 Hip Switch — 1 x 6–8/side\nAnkle Rocker — 1 x 6–8/side",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "CONDITIONAL: Low Box Jump — 2 x 2 only if springy and pain-free; usually none in intensification/check/test/realization",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Recovery Primary — knees, hip flexors, and structural control only\nBackward Sled Drag\n4 x 20 yards • light to moderate\nLeg Extension\n3 x 15 • controlled, 2-second squeeze\nStanding Cable Hip Flexor March\n3 x 10 each leg\nRest - 45 to 60 seconds between movements",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Leg Extension — 2–3 x 12–15\nCable Hip-Flexor March — 2–3 x 8–10/leg",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Low-fatigue support only; Day 4 is NOT a glute-specialization day\nHam Curl 2x10–12 + ONE trunk role 2 sets",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "mandatory",
          prescription: "Backward Sled Drag — 4 x 20 yd light-moderate • ONE total knee/recovery dose",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "OPTIONAL: hand health 1–2 easy sets only if weekly budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: choose ONE — 10–20 min easy walk/bike OR one short mobility/restoration flow. Leave feeling better.",
        },
      ],
    },
    {
      day: 5,
      title: "FRONT SQUAT SUPPORT + CLOSE-GRIP BENCH + CARRY",
      role: "Front-squat support + close-grip bench + carry",
      duration: "75–95 min",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "3–5 min easy + 2 prep drills + front-squat/bench ramp; no warm-up sled layer",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "HPC 4x2; Clean Pull 4x3 @85% (150)",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Front Squat Support — Smolov-lite secondary exposure\n4 x 4 @ 62.5%\nClose-Grip Bench Press — reinforcement\n4 x 5 @ 72.5%\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable Press-Around 2x12–15 (Exposure B)",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "No additional loaded glute slot; weekly roles already supplied by D1 hip thrust/lunge + D3 deadlift\nLat Pulldown 2–3x8–10 + Chest-Supported Row 2x8–10",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "mandatory",
          prescription: "Front Rack Carry 3x25–30 yd",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Optional Sled Push 2–3x20 yd, work-capacity job only",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "No plate pinch by default; finger extension optional",
        },
      ],
    },
  ],
  sourceHash: "820a7e17518a0d0209afe9071ab31dcee59bd1cd5b43d5bfad7bde8dee066397",
} satisfies BlackCrownSourceWeek
