import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_31_SOURCE = {
  week: 31,
  block: 6,
  title: "Strength Intensification / Specificity Bridge",
  days: [
    {
      day: 1,
      title: "HEAVY SQUAT + BENCH SPECIFICITY",
      role: "HEAVY SQUAT + BENCH SPECIFICITY",
      duration: "60–80 min; peak/realization support must not extend the session",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 min\nBackward Sled Drag — 2 trips x 20 yards, light • knee-prep job\nGlute Bridge Iso Hold — 2 x 20 sec\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Box Jump — 4 x 2 • low fatigue\nMed-Ball Chest Pass or Explosive Push-Up — 3 x 3\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Front Squat — intensification top set plus back-off\n1 x 3 @ 72.5%\n1 x 2 @ 80%\n1 x 1 @ 82.5%\n3 x 2 @ 75%\nBench Press — specificity volume\n3 x 4 @ 75%\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Hip Thrust — 3 x 8-10 • with 2-second pause",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row — 3 x 8-10",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
    {
      day: 2,
      title: "BENCH INTENSIFICATION + UPPER BACK",
      role: "BENCH INTENSIFICATION + UPPER BACK",
      duration: "60–80 min; peak/realization support must not extend the session",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 min\nBand Pull-Apart — 2 x 20\nSerratus Wall Slide — 2 x 10\nLight Face Pull — 2 x 15\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Tall Clean or Muscle Clean Drill — 3 x 3 • with empty bar/light load\nHang Power Clean — 4 x 2 • Effort cap: RPE 5-6 • crisp receiving-lift practice\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "ORDER NOTE: Complete protected Bench work first. Perform Strict OHP next, then return to any remaining source-primary support listed below.\n\nBench Press — top set plus back-off\n1 x 3 @ 70%\n1 x 2 @ 77.5%\n1 x 1 @ 80%\n3 x 3 @ 72.5%\nIncline Dumbbell Press\n2 x 8 @ RPE 7 • controlled\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "III",
          title: "PRIMARY — STRICT OHP",
          priority: "mandatory",
          prescription: "3x4 @ 67.5%• STRENGTH / INTENSIFICATION\nPLACEMENT: Day 2 AFTER protected Bench, BEFORE lower-priority support\nQUALITY: Stop at first grind, pain, repeated layback/rib flare, loss of stacked lockout, or meaningful speed drop.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Neutral-Grip Lat Pulldown — 4 x 8-10\nRear Deltoid Fly — 3 x 15",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "Chest-Supported Dumbbell Shrug or Kelso-Style Shrug — 2 x 10-12 • with 2-second squeeze",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
    {
      day: 3,
      title: "HEAVY DEADLIFT + LAT SUPPORT",
      role: "HEAVY DEADLIFT + LAT SUPPORT",
      duration: "60–80 min; peak/realization support must not extend the session",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Walk — 5 min\nHip Hinge Drill — 10 reps\nGlute Bridge — 15 reps\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Broad Jump — 4 x 2 • low fatigue\nKB Swing — 3 x 10 • crisp hinge only\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Deadlift — top set plus back-off\n1 x 3 @ 70%\n1 x 2 @ 77.5%\n1 x 1 @ 80%\n3 x 3 @ 72.5%\nFront Squat Technique\n3 x 3 @ 60%\nAssisted Pull-Up or Pull-Up\n5 x 3-5 • clean reps\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row or Seated Cable Row — 3 x 8-12\nSeated Hamstring Curl — 2 x 10-15",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–12 min easy walk/bike/elliptical only if it improves recovery",
        },
      ],
    },
    {
      day: 4,
      title: "RECOVERY + KNEES + HIP FLEXORS",
      role: "RECOVERY + KNEES + HIP FLEXORS",
      duration: "25–40 min core; ≤45–55 min with optional restoration",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 4–5 min\n90/90 Hip Switch — 1 x 6–8/side\nAnkle Rocker — 1 x 6–8/side",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "CONDITIONAL: Low Box Jump — 2 x 2 only if springy and pain-free; usually none in intensification/check/test/realization",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Recovery Primary — knees, hip flexors, and structural control only\nBackward Sled Drag\n4 x 20 yards • light to moderate\nLeg Extension\n3 x 15 • controlled, 2-second squeeze\nStanding Cable Hip Flexor March\n3 x 10 each leg\nRest - 45 to 60 seconds between movements",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Leg Extension — 2 x 12–15\nCable Hip-Flexor March — 2 x 8–10/leg",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Hamstring Curl — 1–2 x 10–12\nPallof Press OR Side Plank — 1–2 sets",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "mandatory",
          prescription: "Backward Sled Drag — 2–3 x 20 yd light • ONE total knee/recovery dose",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "OPTIONAL: hand health 1–2 easy sets only if weekly budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: choose ONE — 10–20 min easy walk/bike OR one short mobility/restoration flow. Leave feeling better.",
        },
      ],
    },
    {
      day: 5,
      title: "SECONDARY SQUAT + PAUSE BENCH + CLEAN PULL",
      role: "WEEK 32",
      duration: "60–80 min; peak/realization support must not extend the session",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Bike or Walk — 3-5 min\nBackward Sled Drag — 2 trips x 20 yards • knee-prep job\nMini-Band Lateral Walk — 10 steps each direction\nGlute Bridge Iso Hold — 20 sec\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Hang Power Clean — 4 x 2 • Effort cap: RPE 6 • crisp receiving-lift practice\nClean Pull — 4 x 3 • 80%\nRest — 2-3 min between Olympic derivative sets\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Secondary Squat Support — position and speed\n3 x 4 @ 65%\nPause Bench Press — reinforcement\n4 x 4 @ 70%\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable Press-Around — 2 to 3 x 10 to 15",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Lat Pulldown or Assisted Pull-Up — 3 x 8-10",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "CONDITIONAL if grip/traps are Green: Farmer Carry (Trap-Bar Carry acceptable) — 2 to 3 short trips, moderate only if grip is fresh",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Sled Push — 3 trips x 20 yards • work-capacity job only",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
  ],
  sourceHash: "f59918772c21740f7da1aec141946686a967bc3f5792fa0a39c07f5299facfe8",
} satisfies BlackCrownSourceWeek
