import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_05_SOURCE = {
  week: 5,
  block: 1,
  title: "Foundation / Re-Entry",
  days: [
    {
      day: 1,
      title: "LOWER + BENCH FREQUENCY + GLUTES",
      role: "Hard lower-body peak-stress exposure with controlled bench work, glute support, and knee-friendly sled prep.",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Incline Walk or Bike — 3 to 5 minutes easy\nBackward Sled Drag — 3 x 20 yards • light • knee-prep job\nMini-Band Lateral Walk — 2 x 10 • steps each direction\nGlute Bridge Isometric Hold — 2 x 20 seconds\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Hang Power Clean — 4 x 2 • 70%\nBox Jump — 3 x 2\nKettlebell Swing — 2 x 8 • crisp reps\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Front Squat — Sheiko base wave\n1 x 5 @ 75%\n1 x 5 @ 80%\n1 x 4 @ 82.5%\n1 x 3 @ 85%\n1 x 5 @ 80%\nBench Press — frequency practice\n4 x 3 @ 80%\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Hip Thrust — 3 x 8-10 • with 2-second pause\nSnatch-Grip RDL (or Hamstring Curl if recovery constrained) — 3 x 8-10",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row — 3 x 8-10\nLeg Extension — 3 x 12-15\nCONDITIONAL: Step-Up — 8 each leg",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
    {
      day: 2,
      title: "BENCH VOLUME + UPPER BACK / YOKE / ARMS",
      role: "Moderate upper day with the heaviest bench wave of Block I, controlled back balance, and low-fatigue rotational skill.",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike — 5 minutes\nBand Pull-Apart — 2 x 20\nScapular Push-Up — 2 x 10\nFace Pull — 2 x 15\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Medicine Ball Chest Pass — 3 x 3\nExplosive Push-Up — 3 x 3\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "ORDER NOTE: Complete protected Bench work first. Perform Strict OHP next, then return to any remaining source-primary support listed below.\n\nBench Press — upper-volume exposure\n4 x 4 @ 75%\nIncline Dumbbell Press\n3 x 8-10 @ RPE 7\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "III",
          title: "PRIMARY — STRICT OHP",
          priority: "mandatory",
          prescription: "3x4 @ 65%• DEVELOPMENT\nPLACEMENT: Day 2 AFTER protected Bench, BEFORE lower-priority support\nQUALITY: Stop at first grind, pain, repeated layback/rib flare, loss of stacked lockout, or meaningful speed drop.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Neutral-Grip Lat Pulldown — 4 x 8-10\nRear Deltoid Fly — 3 x 15",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "Chest-Supported Dumbbell Shrug or Kelso-Style Shrug — 2 x 10-12 • with 2-second squeeze",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
    {
      day: 3,
      title: "DEADLIFT + SECONDARY SQUAT + PULL",
      role: "Hardest pull exposure of Block I with controlled accessories and no unnecessary hinge stacking.",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Walk — 5 minutes\nHip Hinge Drill — 2 x 10\nGlute Bridge — 2 x 15\nBird Dog — 2 x 8 each side\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Broad Jump — 3 x 2\nKettlebell Swing — 2 x 8 • crisp reps\nDeadlift Primer — 2 x 2 • 55%\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Deadlift — strength wave\n1 x 3 @ 75%\n1 x 3 @ 80%\n1 x 2 @ 85%\n1 x 1 @ 87.5%\n1 x 3 @ 80%\nFront Squat Technique\n3 x 4 @ 67.5%\nAssisted Pull-Up or Pull-Up\n5 x 3-5 • clean reps\nRest - 2 to 3 minutes between primary work sets",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Chest-Supported Row or Seated Cable Row — 3 x 8-12\nSeated Hamstring Curl — 3 x 10-15\nCONDITIONAL low-back durability: Sorenson Hold, Reverse Hyper, or Bird Dog Hold — 3 x 20-30 seconds",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–12 min easy walk/bike/elliptical only if it improves recovery",
        },
      ],
    },
    {
      day: 4,
      title: "RECOVERY + KNEES + HIP FLEXORS",
      role: "Structural support and recovery. This protects the peak week instead of adding hidden fatigue.",
      duration: "25–40 min core; ≤45–55 min with optional restoration",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 4–5 min\n90/90 Hip Switch — 1 x 6–8/side\nAnkle Rocker — 1 x 6–8/side",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "CONDITIONAL: Low Box Jump — 2 x 2 only if springy and pain-free; usually none in intensification/check/test/realization",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Recovery Primary — knees, hip flexors, and structural control only\nBackward Sled Drag\n4 x 20 yards • light to moderate\nLeg Extension\n3 x 15 • controlled, 2-second squeeze\nStanding Cable Hip Flexor March\n3 x 10 each leg\nRest - 45 to 60 seconds between movements",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Leg Extension — 3 x 12–15\nCable Hip-Flexor March — 3 x 8–10/leg",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Hamstring Curl — 2 x 10–12\nPallof Press OR Side Plank — 2 sets",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "mandatory",
          prescription: "Backward Sled Drag — 4 x 20 yd light • ONE total knee/recovery dose",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "OPTIONAL: hand health 1–2 easy sets only if weekly budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: choose ONE — 10–20 min easy walk/bike OR one short mobility/restoration flow. Leave feeling better.",
        },
      ],
    },
    {
      day: 5,
      title: "SECONDARY SQUAT + CLOSE-GRIP BENCH + CARRY",
      role: "Peak-stress reinforcement with clean Olympic power, strong bench support, controlled lower-body volume, and sled capacity.",
      duration: "65–90 min; cut bottom-up rather than compressing primary rest",
      status: "STANDARD / BLOCK-SPECIFIC",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Bike or Walk — 3 to 5 minutes easy\nBackward Sled Drag — 2 x 20 yards • light • knee-prep job\nMini-Band Lateral Walk — 2 x 10 • steps each direction\nGlute Bridge Isometric Hold — 2 x 20 seconds\nLift-specific ramp sets — build to first work set; do not create fatigue",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Hang Power Clean — 4 x 2 • 70%\nClean Pull — 4 x 2 • 85%\nExplosive Push-Up — 3 x 3\nQuality cap: stop/reduce if timing, landing, bar speed, grip, or receiving position deteriorates.",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Belt Squat Strength Volume\n4 x 8 @ RPE 7 • controlled\nClose-Grip Bench Press — reinforcement\n4 x 3 @ 80%\nChest-Supported Row\n4 x 8-10\nRest - 2 minutes between primary work sets",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable Press-Around — 2 to 3 x 10 to 15",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Lat Pulldown or Assisted Pull-Up — 3 x 8-10\nLeg Extension — 2 to 3 x 12 to 15",
        },
        {
          ordinal: "V",
          title: "CROWN — YOKE / CARRY",
          priority: "conditional",
          prescription: "Farmer Carry (Trap-Bar Carry acceptable) — 2 to 3 short trips, moderate only if grip is fresh",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Prowler Push — 3 x 25 yards • moderate • work-capacity job only",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "Finger Extension — 1–2 easy sets of 20 only if hand-health budget is open",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "OPTIONAL: 8–15 min easy walk/bike; one finisher maximum",
        },
      ],
    },
  ],
  sourceHash: "821742153f62337e66b8d26a4790f9272be59aedfe1d15e7bb91228ff5c89c69",
} satisfies BlackCrownSourceWeek
