import type { BlackCrownSourceWeek } from '../source-types'

export const BLACK_CROWN_WEEK_24_SOURCE = {
  week: 24,
  block: 4,
  title: "Strength Consolidation / Rebuild",
  days: [
    {
      day: 1,
      title: "BACK SQUAT VERIFIED 1RM TEST",
      role: "Establish the verified back-squat 1RM after a full taper, using three governed attempts.",
      duration: "20–60 min depending local test/check day",
      status: "VERIFIED 1RM TEST",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes\nBackward Sled Drag — 2 x 20 yards • light\nHip Airplane — 2 x 5 each side\nEmpty Bar Patterning — 2 easy sets",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump — 3 x 2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Back Squat — Set projected third on MAXES before test day\nBack Squat - Attempt 1 — Set projected third on MAXES before test day\nBack Squat - Attempt 2 — Set projected third on MAXES before test day\nBack Squat - Attempt 3 — Set projected third on MAXES before test day\nRest 3-5 minutes before the final warm-up and 5-8 minutes between attempts. Enter Made / Missed on MAXES. Highest successful attempt is the verified 1RM. No fourth attempt.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
    {
      day: 2,
      title: "BENCH PRESS VERIFIED 1RM TEST",
      role: "Establish the verified competition-style bench 1RM with a controlled pause and safe handoff.",
      duration: "20–60 min depending local test/check day",
      status: "VERIFIED 1RM TEST",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes\nBackward Sled Drag — 2 x 20 yards • light\nHip Airplane — 2 x 5 each side\nEmpty Bar Patterning — 2 easy sets",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump — 3 x 2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Bench Press — Set projected third on MAXES before test day\nBench Press - Attempt 1 — Set projected third on MAXES before test day\nBench Press - Attempt 2 — Set projected third on MAXES before test day\nBench Press - Attempt 3 — Set projected third on MAXES before test day\nRest 3-5 minutes before the final warm-up and 5-8 minutes between attempts. Enter Made / Missed on MAXES. Highest successful attempt is the verified 1RM. No fourth attempt.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
    {
      day: 3,
      title: "RECOVERY / JOINT RESTORATION",
      role: "Restore joints and readiness between verified test days without adding meaningful fatigue.",
      duration: "20–60 min depending local test/check day",
      status: "VERIFIED 1RM TEST",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike — 10 minutes easy\n90/90 Hip Mobility — 2 x 5 each side\nSerratus Wall Slide — 2 x 10",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "None",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Mobility Flow — 2 easy rounds",
        },
        {
          ordinal: "IV",
          title: "SECONDARY / SPECIALIZATION",
          priority: "mandatory",
          prescription: "Cable March — 2 x 10 each side\nLeg Extension — 2 x 15 • easy",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
    {
      day: 4,
      title: "FRONT SQUAT VERIFIED 1RM TEST",
      role: "Establish the verified front-squat 1RM after recovery, with rack position and trunk control protected.",
      duration: "20–60 min depending local test/check day",
      status: "VERIFIED 1RM TEST",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes\nBackward Sled Drag — 2 x 20 yards • light\nHip Airplane — 2 x 5 each side\nEmpty Bar Patterning — 2 easy sets",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump — 3 x 2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Front Squat — Set projected third on MAXES before test day\nFront Squat - Attempt 1 — Set projected third on MAXES before test day\nFront Squat - Attempt 2 — Set projected third on MAXES before test day\nFront Squat - Attempt 3 — Set projected third on MAXES before test day\nRest 3-5 minutes before the final warm-up and 5-8 minutes between attempts. Enter Made / Missed on MAXES. Highest successful attempt is the verified 1RM. No fourth attempt.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
    {
      day: 5,
      title: "DEADLIFT VERIFIED 1RM TEST",
      role: "Establish the verified deadlift 1RM last, after grip and posterior-chain fatigue have been minimized.",
      duration: "20–60 min depending local test/check day",
      status: "VERIFIED 1RM TEST",
      sections: [
        {
          ordinal: "I",
          title: "WARM-UP",
          priority: "mandatory",
          prescription: "Easy Bike or Walk — 5 minutes\nBackward Sled Drag — 2 x 20 yards • light\nHip Airplane — 2 x 5 each side\nEmpty Bar Patterning — 2 easy sets",
        },
        {
          ordinal: "II",
          title: "PRIMER / POWER",
          priority: "conditional",
          prescription: "Low Box Jump — 3 x 2",
        },
        {
          ordinal: "III",
          title: "PRIMARY",
          priority: "mandatory",
          prescription: "Deadlift — Set projected third on MAXES before test day\nDeadlift - Attempt 1 — Set projected third on MAXES before test day\nDeadlift - Attempt 2 — Set projected third on MAXES before test day\nDeadlift - Attempt 3 — Set projected third on MAXES before test day\nRest 3-5 minutes before the final warm-up and 5-8 minutes between attempts. Enter Made / Missed on MAXES. Highest successful attempt is the verified 1RM. No fourth attempt.",
        },
        {
          ordinal: "V",
          title: "CROWN — STRUCTURAL SUPPORT",
          priority: "conditional",
          prescription: "Local source recovery support only; keep easy/RPE 6 when prescribed.",
        },
        {
          ordinal: "VI",
          title: "CIRCUIT / LOW-INTENSITY WORK — SLED / GPP",
          priority: "optional",
          prescription: "Only source-local light sled if explicitly prescribed; no second sled block.",
        },
        {
          ordinal: "VII",
          title: "GRIP / HAND HEALTH",
          priority: "optional",
          prescription: "None by default.",
        },
        {
          ordinal: "VIII",
          title: "CONDITIONING / RECOVERY",
          priority: "optional",
          prescription: "Easy restoration only if it improves recovery; no hard conditioning.",
        },
      ],
    },
  ],
  sourceHash: "ac20771ed574cee6d9f263679938bb2015f62bd87c65ef0bea34c5d3f59a8a9c",
} satisfies BlackCrownSourceWeek
